version: '3.3'

services:
  mysql:
    image: mariadb:latest
    env_file: .env
    environment:
      - TZ='America/Lima'
    restart: 'always'
    volumes:
      - ./db:/var/lib/mysql
      - ./my-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - APP_NETWORK

  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: always
    ports:
      - $ENV_PORT_ADMINER:8080
    networks:
      - APP_NETWORK

  wordpress:
    depends_on:
      - mysql
    image: wordpress:php7.3-fpm-alpine
    ports:
      - $ENV_PORT_WORDPRESS:80
    restart: always
    volumes:
      - ./public:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - APP_NETWORK

networks:
  APP_NETWORK:
    name: $APP_NETWORK
