version: '3.7'

services:
  wordpress-fpm:
    image: wordpress:5-fpm-alpine
    volumes:
      - ./public/www:/var/www/html
    depends_on: ['db']
    links: ['db']
    #ports: ['${MY_ENV_PORT_WORDPRESS}:80']
    ports: ['${MY_ENV_PORT_FPM}:9000']
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports: ['${MY_ENV_NGINX}:80']
    links: ['wordpress-fpm']
