version: '3.7'

services:
  db:
    image: mariadb:10
    env_file:
      - .env
    environment:
      - TZ='America/Lima'
    restart: always
    ports:
      - ${MY_ENV_PORT_DB}:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./my-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - ${MY_ENV_PORT_ADMINER}:8080
