version: '3.7'

services:
  db:
    image: mariadb:10
    env_file:
      - .env
    environment:
      - TZ='America/Lima'
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
      #- ./my-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    image: wordpress:5.6.2-php7.3-fpm-alpine
    volumes:
      - ./data/html:/var/www/html
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on: ['db']
    links: ['db']
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}

  nginx:
    depends_on: ['wordpress']
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports: ['${MY_ENV_NGINX}:80']
    links: ['wordpress']

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - ${MY_ENV_PORT_ADMINER}:8080
