version: '3.3'

services:
  db:
    container_name: db
    image: mysql:5.7.33
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - TZ='America/Lima'
    restart: 'always'
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./my-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080
  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    ports:
      - '6060:80'
    restart: always
    volumes:
      - ./public:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
