version: '3.5'

services:
  mysql:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - TZ='America/Lima'
    restart: unless-stopped
    ports:
      - ${ENV_PORT_DB}:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./my-config:/etc/mysql/conf.d
    networks:
      - APP_NETWORK

  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - ${ENV_PORT_ADMINER}:8080
    networks:
      - APP_NETWORK

  wordpress:
    depends_on:
      - mysql
    image: wordpress:php7.3-fpm-alpine
    ports:
      - ${ENV_PORT_WORDPRESS}:80
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=wp_
    networks:
      - APP_NETWORK

networks:
  APP_NETWORK:
    name: ${APP_NETWORK}
