version: '3.7'

services:
  db:
    image: mariadb:10
    env_file:
      - .env
    environment:
      - TZ='America/Lima'
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      #- ./my-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    image: wordpress:5
    volumes:
      - ./public:/var/www/html
    depends_on: ['db']
    links: ['db']
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - ${MY_ENV_PORT_ADMINER}:8080
