version: '3.7'

services:
  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - TZ='America/Lima'
    restart: unless-stopped
    ports:
      - ${MY_ENV_PORT_DB}:3306
    volumes:
      - ./db_data:/var/lib/mysql
      #- ./my-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - APP_NETWORK

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    ports:
      - ${MY_ENV_PORT_WORDPRESS}:80
      - ${MY_ENV_PORT_FPM}:9000
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:${MY_ENV_PORT_DB}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - APP_NETWORK

  adminer:
    depends_on:
      - db
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - ${MY_ENV_PORT_ADMINER}:8080
    networks:
      - APP_NETWORK

networks:
  APP_NETWORK:
    name: ${MY_ENV_APP_NETWORK}
